import Constants from 'expo-constants';

export const API_BASE_URL = Constants.expoConfig?.extra?.apiUrl || 'http://localhost:5000/api';

export interface SelectOption {
  value: string;
  label: string;
}

export interface ProblemTypeOption {
  value: string;
  label: string;
  icon: string;
}

export interface LanguageOption {
  value: 'en' | 'hi' | 'mixed';
  label: string;
  nativeLabel: string;
  description: string;
}

export const INDIAN_STATES: SelectOption[] = [
  { value: 'andhra_pradesh', label: 'Andhra Pradesh' },
  { value: 'arunachal_pradesh', label: 'Arunachal Pradesh' },
  { value: 'assam', label: 'Assam' },
  { value: 'bihar', label: 'Bihar' },
  { value: 'chhattisgarh', label: 'Chhattisgarh' },
  { value: 'goa', label: 'Goa' },
  { value: 'gujarat', label: 'Gujarat' },
  { value: 'haryana', label: 'Haryana' },
  { value: 'himachal_pradesh', label: 'Himachal Pradesh' },
  { value: 'jharkhand', label: 'Jharkhand' },
  { value: 'karnataka', label: 'Karnataka' },
  { value: 'kerala', label: 'Kerala' },
  { value: 'madhya_pradesh', label: 'Madhya Pradesh' },
  { value: 'maharashtra', label: 'Maharashtra' },
  { value: 'manipur', label: 'Manipur' },
  { value: 'meghalaya', label: 'Meghalaya' },
  { value: 'mizoram', label: 'Mizoram' },
  { value: 'nagaland', label: 'Nagaland' },
  { value: 'odisha', label: 'Odisha' },
  { value: 'punjab', label: 'Punjab' },
  { value: 'rajasthan', label: 'Rajasthan' },
  { value: 'sikkim', label: 'Sikkim' },
  { value: 'tamil_nadu', label: 'Tamil Nadu' },
  { value: 'telangana', label: 'Telangana' },
  { value: 'tripura', label: 'Tripura' },
  { value: 'uttar_pradesh', label: 'Uttar Pradesh' },
  { value: 'uttarakhand', label: 'Uttarakhand' },
  { value: 'west_bengal', label: 'West Bengal' },
  { value: 'andaman_nicobar', label: 'Andaman & Nicobar Islands' },
  { value: 'chandigarh', label: 'Chandigarh' },
  { value: 'dadra_nagar_haveli', label: 'Dadra & Nagar Haveli and Daman & Diu' },
  { value: 'daman_diu', label: 'Daman & Diu' },
  { value: 'delhi', label: 'Delhi' },
  { value: 'jammu_kashmir', label: 'Jammu & Kashmir' },
  { value: 'ladakh', label: 'Ladakh' },
  { value: 'lakshadweep', label: 'Lakshadweep' },
  { value: 'puducherry', label: 'Puducherry' },
];

export const DISTRICTS: Record<string, SelectOption[]> = {
  delhi: [
    { value: 'central_delhi', label: 'Central Delhi' },
    { value: 'east_delhi', label: 'East Delhi' },
    { value: 'new_delhi', label: 'New Delhi' },
    { value: 'north_delhi', label: 'North Delhi' },
    { value: 'north_east_delhi', label: 'North East Delhi' },
    { value: 'north_west_delhi', label: 'North West Delhi' },
    { value: 'shahdara', label: 'Shahdara' },
    { value: 'south_delhi', label: 'South Delhi' },
    { value: 'south_east_delhi', label: 'South East Delhi' },
    { value: 'south_west_delhi', label: 'South West Delhi' },
    { value: 'west_delhi', label: 'West Delhi' },
  ],
  uttar_pradesh: [
    { value: 'agra', label: 'Agra' },
    { value: 'aligarh', label: 'Aligarh' },
    { value: 'prayagraj', label: 'Allahabad (Prayagraj)' },
    { value: 'ambedkar_nagar', label: 'Ambedkar Nagar' },
    { value: 'amethi', label: 'Amethi' },
    { value: 'amroha', label: 'Amroha' },
    { value: 'auraiya', label: 'Auraiya' },
    { value: 'azamgarh', label: 'Azamgarh' },
    { value: 'baghpat', label: 'Baghpat' },
    { value: 'bahraich', label: 'Bahraich' },
    { value: 'ballia', label: 'Ballia' },
    { value: 'balrampur', label: 'Balrampur' },
    { value: 'banda', label: 'Banda' },
    { value: 'barabanki', label: 'Barabanki' },
    { value: 'bareilly', label: 'Bareilly' },
    { value: 'basti', label: 'Basti' },
    { value: 'bijnor', label: 'Bijnor' },
    { value: 'budaun', label: 'Budaun' },
    { value: 'bulandshahr', label: 'Bulandshahr' },
    { value: 'chandauli', label: 'Chandauli' },
    { value: 'chitrakoot', label: 'Chitrakoot' },
    { value: 'deoria', label: 'Deoria' },
    { value: 'etah', label: 'Etah' },
    { value: 'etawah', label: 'Etawah' },
    { value: 'farrukhabad', label: 'Farrukhabad' },
    { value: 'fatehpur', label: 'Fatehpur' },
    { value: 'firozabad', label: 'Firozabad' },
    { value: 'gautam_buddha_nagar', label: 'Gautam Buddha Nagar (Noida)' },
    { value: 'ghaziabad', label: 'Ghaziabad' },
    { value: 'ghazipur', label: 'Ghazipur' },
    { value: 'gonda', label: 'Gonda' },
    { value: 'gorakhpur', label: 'Gorakhpur' },
    { value: 'hamirpur', label: 'Hamirpur' },
    { value: 'hardoi', label: 'Hardoi' },
    { value: 'hathras', label: 'Hathras' },
    { value: 'jaunpur', label: 'Jaunpur' },
    { value: 'jhansi', label: 'Jhansi' },
    { value: 'kannauj', label: 'Kannauj' },
    { value: 'kanpur_nagar', label: 'Kanpur Nagar' },
    { value: 'kanpur_dehat', label: 'Kanpur Dehat' },
    { value: 'kasganj', label: 'Kasganj' },
    { value: 'kaushambi', label: 'Kaushambi' },
    { value: 'kushinagar', label: 'Kushinagar' },
    { value: 'lakhimpur_kheri', label: 'Lakhimpur Kheri' },
    { value: 'lalitpur', label: 'Lalitpur' },
    { value: 'lucknow', label: 'Lucknow' },
    { value: 'maharajganj', label: 'Maharajganj' },
    { value: 'mathura', label: 'Mathura' },
    { value: 'mau', label: 'Mau' },
    { value: 'meerut', label: 'Meerut' },
  ],
  haryana: [
    { value: 'ambala', label: 'Ambala' },
    { value: 'bhiwani', label: 'Bhiwani' },
    { value: 'charkhi_dadri', label: 'Charkhi Dadri' },
    { value: 'faridabad', label: 'Faridabad' },
    { value: 'fatehabad', label: 'Fatehabad' },
    { value: 'gurugram', label: 'Gurugram' },
    { value: 'hisar', label: 'Hisar' },
    { value: 'jhajjar', label: 'Jhajjar' },
    { value: 'jind', label: 'Jind' },
    { value: 'kaithal', label: 'Kaithal' },
    { value: 'karnal', label: 'Karnal' },
    { value: 'kurukshetra', label: 'Kurukshetra' },
    { value: 'mahendragarh', label: 'Mahendragarh' },
    { value: 'nuh', label: 'Nuh' },
    { value: 'palwal', label: 'Palwal' },
    { value: 'panchkula', label: 'Panchkula' },
    { value: 'panipat', label: 'Panipat' },
    { value: 'rewari', label: 'Rewari' },
    { value: 'rohtak', label: 'Rohtak' },
    { value: 'sirsa', label: 'Sirsa' },
    { value: 'sonipat', label: 'Sonipat' },
    { value: 'yamunanagar', label: 'Yamunanagar' },
  ],
  rajasthan: [
    { value: 'ajmer', label: 'Ajmer' },
    { value: 'alwar', label: 'Alwar' },
    { value: 'banswara', label: 'Banswara' },
    { value: 'baran', label: 'Baran' },
    { value: 'barmer', label: 'Barmer' },
    { value: 'bharatpur', label: 'Bharatpur' },
    { value: 'bhilwara', label: 'Bhilwara' },
    { value: 'bikaner', label: 'Bikaner' },
    { value: 'bundi', label: 'Bundi' },
    { value: 'chittorgarh', label: 'Chittorgarh' },
    { value: 'churu', label: 'Churu' },
    { value: 'dausa', label: 'Dausa' },
    { value: 'dholpur', label: 'Dholpur' },
    { value: 'dungarpur', label: 'Dungarpur' },
    { value: 'hanumangarh', label: 'Hanumangarh' },
    { value: 'jaipur', label: 'Jaipur' },
    { value: 'jaisalmer', label: 'Jaisalmer' },
    { value: 'jalore', label: 'Jalore' },
    { value: 'jhalawar', label: 'Jhalawar' },
    { value: 'jhunjhunu', label: 'Jhunjhunu' },
    { value: 'jodhpur', label: 'Jodhpur' },
    { value: 'karauli', label: 'Karauli' },
    { value: 'kota', label: 'Kota' },
    { value: 'nagaur', label: 'Nagaur' },
    { value: 'pali', label: 'Pali' },
    { value: 'pratapgarh', label: 'Pratapgarh' },
    { value: 'rajsamand', label: 'Rajsamand' },
    { value: 'sawai_madhopur', label: 'Sawai Madhopur' },
    { value: 'sikar', label: 'Sikar' },
    { value: 'sirohi', label: 'Sirohi' },
    { value: 'sri_ganganagar', label: 'Sri Ganganagar' },
    { value: 'tonk', label: 'Tonk' },
    { value: 'udaipur', label: 'Udaipur' },
  ],
  maharashtra: [
    { value: 'mumbai_city', label: 'Mumbai City' },
    { value: 'mumbai_suburban', label: 'Mumbai Suburban' },
    { value: 'thane', label: 'Thane' },
    { value: 'pune', label: 'Pune' },
    { value: 'nagpur', label: 'Nagpur' },
    { value: 'nashik', label: 'Nashik' },
    { value: 'chhatrapati_sambhajinagar', label: 'Aurangabad (Chhatrapati Sambhajinagar)' },
    { value: 'solapur', label: 'Solapur' },
    { value: 'kolhapur', label: 'Kolhapur' },
    { value: 'satara', label: 'Satara' },
    { value: 'sangli', label: 'Sangli' },
    { value: 'ratnagiri', label: 'Ratnagiri' },
    { value: 'sindhudurg', label: 'Sindhudurg' },
    { value: 'raigad', label: 'Raigad' },
    { value: 'palghar', label: 'Palghar' },
    { value: 'ahmednagar', label: 'Ahmednagar' },
    { value: 'jalgaon', label: 'Jalgaon' },
    { value: 'dhule', label: 'Dhule' },
    { value: 'nandurbar', label: 'Nandurbar' },
    { value: 'amravati', label: 'Amravati' },
  ],
  karnataka: [
    { value: 'bangalore_urban', label: 'Bangalore Urban' },
    { value: 'bangalore_rural', label: 'Bangalore Rural' },
    { value: 'mysuru', label: 'Mysuru' },
    { value: 'dakshina_kannada', label: 'Mangaluru (Dakshina Kannada)' },
    { value: 'belagavi', label: 'Belagavi' },
    { value: 'dharwad', label: 'Dharwad' },
    { value: 'hubli', label: 'Hubli' },
    { value: 'kalaburagi', label: 'Kalaburagi' },
    { value: 'bellary', label: 'Bellary' },
    { value: 'raichur', label: 'Raichur' },
    { value: 'shimoga', label: 'Shimoga' },
    { value: 'tumkur', label: 'Tumkur' },
    { value: 'hassan', label: 'Hassan' },
    { value: 'mandya', label: 'Mandya' },
    { value: 'chikmagalur', label: 'Chikmagalur' },
    { value: 'udupi', label: 'Udupi' },
    { value: 'uttara_kannada', label: 'Uttara Kannada' },
    { value: 'bidar', label: 'Bidar' },
    { value: 'gadag', label: 'Gadag' },
    { value: 'haveri', label: 'Haveri' },
  ],
};

export const PROBLEM_TYPES: ProblemTypeOption[] = [
  { value: 'property_dispute', label: 'Property Dispute', icon: 'home-city' },
  { value: 'criminal_matter', label: 'Criminal Matter', icon: 'gavel' },
  { value: 'family_matter', label: 'Family Matter', icon: 'account-group' },
  { value: 'consumer_complaint', label: 'Consumer Complaint', icon: 'cart-alert' },
  { value: 'employment_issue', label: 'Employment Issue', icon: 'briefcase' },
  { value: 'business_contract', label: 'Business/Contract', icon: 'file-document-edit' },
  { value: 'rti_information', label: 'RTI/Information', icon: 'information' },
  { value: 'traffic_vehicle', label: 'Traffic/Vehicle', icon: 'car' },
  { value: 'cyber_crime', label: 'Cyber Crime', icon: 'laptop' },
  { value: 'tenant_landlord', label: 'Tenant/Landlord', icon: 'home-account' },
  { value: 'cheque_bounce', label: 'Cheque Bounce', icon: 'cash-remove' },
  { value: 'domestic_violence', label: 'Domestic Violence', icon: 'shield-alert' },
  { value: 'other', label: 'Other', icon: 'dots-horizontal' },
];

export const SUGGESTED_QUESTIONS: Record<string, string[]> = {
  property_dispute: [
    'How do I verify property title and ownership?',
    'What is the process to file a property dispute case?',
    'How to get an encumbrance certificate?',
    'What are my rights as a property buyer?',
  ],
  criminal_matter: [
    'How do I file an FIR under BNSS?',
    'What are my rights if arrested?',
    'How does bail work under the new BNSS?',
    'What is the difference between cognizable and non-cognizable offences?',
  ],
  family_matter: [
    'What are the grounds for divorce in India?',
    'How is child custody decided?',
    'How to file for maintenance?',
    'What is the process for mutual consent divorce?',
  ],
  consumer_complaint: [
    'How to file a consumer complaint online?',
    'What compensation can I claim?',
    'What is the time limit for filing consumer case?',
    'Which consumer forum should I approach?',
  ],
  employment_issue: [
    'What are my rights regarding wrongful termination?',
    'How to file a complaint with Labour Commissioner?',
    'What is the process for claiming unpaid wages?',
    'How does the PF/ESI grievance process work?',
  ],
  business_contract: [
    'How to enforce a contract in India?',
    'What remedies exist for breach of contract?',
    'How to send a legal notice?',
    'What is the arbitration process?',
  ],
  rti_information: [
    'How to file an RTI application?',
    'What is the fee for RTI?',
    'How to file first appeal under RTI?',
    'What information can be sought under RTI?',
  ],
  traffic_vehicle: [
    'What are the penalties under new Motor Vehicle Act?',
    'How to challenge a traffic challan?',
    'What to do after a road accident?',
    'How to claim motor insurance?',
  ],
  cyber_crime: [
    'How to report cyber crime online?',
    'What are the laws against online fraud?',
    'How to file complaint for social media harassment?',
    'What is the process for data theft complaint?',
  ],
  tenant_landlord: [
    'What are tenant rights in India?',
    'How to file for eviction?',
    'What is the process for rent agreement registration?',
    'How to recover security deposit?',
  ],
  cheque_bounce: [
    'What is the legal process for cheque bounce?',
    'How to send legal notice under Section 138 NI Act?',
    'What is the time limit for cheque bounce case?',
    'What compensation can I claim?',
  ],
  domestic_violence: [
    'How to file a domestic violence complaint?',
    'What protection orders are available?',
    'How to get emergency protection?',
    'What rights do I have under DV Act?',
  ],
  other: [
    'What legal rights do I have in this situation?',
    'How do I find a lawyer near me?',
    'What is the process for sending a legal notice?',
    'How do I approach the court?',
  ],
};

export const LANGUAGES: LanguageOption[] = [
  {
    value: 'en',
    label: 'English',
    nativeLabel: 'English',
    description: 'All responses in English',
  },
  {
    value: 'hi',
    label: 'Hindi',
    nativeLabel: '\u0939\u093f\u0928\u094d\u0926\u0940',
    description: '\u0938\u092d\u0940 \u0909\u0924\u094d\u0924\u0930 \u0939\u093f\u0928\u094d\u0926\u0940 \u092e\u0947\u0902',
  },
  {
    value: 'mixed',
    label: 'Hinglish',
    nativeLabel: 'Hinglish',
    description: 'Mix of Hindi & English',
  },
];

export const COLORS = {
  primary: '#1a237e',
  accent: '#ff8f00',
  background: '#ffffff',
  surface: '#f5f5f5',
  error: '#d32f2f',
  text: '#212121',
  textSecondary: '#757575',
} as const;
